publishDir = "docs"
relativeURLs = true

baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stenio HQ"
theme = "minimo"
# theme = "ananke"
disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[params.info]
description = "A hub for my current interests"
title404 = "Oooops, nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Stenio Ferreira"
startYear = "2020"
suffix = " | Powered by [Hugo](https://gohugo.io/) & [Minimo Theme](https://github.com/MunifTanjim/minimo)."

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = false
accentColor = "#ffcd00"
hideMainMenu = true

[params.sidebar]
enable = true

[params.widgets]
# header = ["breadcrumbs"]
# homepage = ["recent_posts"]
sidebar = ["about","social_menu","sidebar_menu","taxonomy_cloud"]
#footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "stenio123" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[social_menu]
title = ""                            # default: ""
platforms = ["github","twitter","linkedin"]

[params.social]

# codepen = "MunifTanjim"
# email = "contact@example.com"
# facebook = "MunifTanjim"
github = "stenio123"
# gitlab = "MunifTanjim"
# instagram = "MunifTanjim"
linkedin = "stenio"
twitter = "stenio123"
# telegram = "MunifTanjim"
# google_scholar = "qc6CJjYAAAAJ"
# youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = false

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"